# Generated by Django 3.0.6 on 2020-05-27 12:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('dateId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Date')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(blank=True, max_length=30, null=True)),
                ('mobileNo', models.CharField(blank=True, max_length=10, null=True)),
                ('dates', models.ManyToManyField(related_name='users', through='accounts.Transaction', to='accounts.Date')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User'),
        ),
        migrations.CreateModel(
            name='AccountInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('openDate', models.DateField(default=datetime.date.today)),
                ('closeDate', models.DateField(default=datetime.date(2020, 8, 25))),
                ('closedDate', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='open', max_length=15)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User')),
            ],
        ),
    ]
