# Generated by Django 3.0.6 on 2020-05-31 14:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinfo',
            name='closeDate',
            field=models.DateField(default=datetime.date(2020, 8, 29)),
        ),
        migrations.AlterField(
            model_name='user',
            name='firstName',
            field=models.CharField(max_length=60),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=70)),
                ('amount', models.IntegerField()),
                ('dateId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Date')),
            ],
        ),
    ]
